Elevator.PhotoJunk.Site/Models/Album/AlbumEditModel.cs
namespace Elevator.PhotoJunk.Site.Models.Album
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.Web;
	using Elevator.PhotoJunk.Site.Validators;

	[AlbumEditModel]
	public class AlbumEditModel
	{
		public bool IsNew { get; set; }

		public Guid Id { get; set; }
		public Guid AuthorId { get; set; }

		[Required]
		[Display(Name = "Title")]
		[DataType(DataType.Text)]
		public string Title { get; set; }

		[Display(Name = "Description")]
		[DisplayFormat(ConvertEmptyStringToNull = false)]
		[DataType(DataType.MultilineText)]
		public string Description { get; set; }

		[Display(Name = "Cover")]
		[FileSize("MaxImageSizeKB")]
		[FileMimeType("SupportedImageMimeTypes")]
		public HttpPostedFileBase CoverImageFile { get; set; }
		public string CoverImageFileName { get; set; }
	}
}

Elevator.PhotoJunk.Site/Models/Album/AlbumManageModel.cs
namespace Elevator.PhotoJunk.Site.Models.Album
{
	using System.Collections.Generic;

	public class AlbumManageModel
	{
		public AlbumThumbnail Album { get; set; }
		public List<PhotoCheck> Photos { get; set; }
	}
}

Elevator.PhotoJunk.Site/Models/Album/AlbumSearchModel.cs
namespace Elevator.PhotoJunk.Site.Models.Album
{
	using System.ComponentModel.DataAnnotations;

	public class AlbumSearchModel
	{
		[Display(Name = "Title")]
		[DataType(DataType.Text)]
		public string Title { get; set; }

		[Display(Name = "Descriprion")]
		[DataType(DataType.MultilineText)]
		public string Descriprion { get; set; }

		[Display(Name = "Author name")]
		[DataType(DataType.Text)]
		public string AuthorName { get; set; }
	}
}

Elevator.PhotoJunk.Site/Models/Album/AlbumShowModel.cs
namespace Elevator.PhotoJunk.Site.Models.Album
{
	using System;
	using Elevator.PhotoJunk.Logic.Pagination;
	using Elevator.PhotoJunk.Site.Models.Photo;

	public class AlbumShowModel
	{
		public Guid Id { get; set; }
		public string AuthorName { get; set; }
		public string AuthorEmail { get; set; }
		public Guid AuthorId { get; set; }
		public string Title { get; set; }
		public string Description { get; set; }
		public DateTime UploadDate { get; set; }
		public string CoverImageFileName { get; set; }

		public PagedData<PhotoThumbnail> Photos { get; set; }
	}
}

Elevator.PhotoJunk.Site/Models/Album/AlbumThumbnail.cs
namespace Elevator.PhotoJunk.Site.Models.Album
{
	using System;

	public class AlbumThumbnail
	{
		public Guid AlbumId { get; set; }
		public string AuthorName { get; set; }
		public string AuthorEmail { get; set; }
		public string Title { get; set; }
		public string CoverFileName { get; set; }
	}
}

Elevator.PhotoJunk.Site/Models/Album/PhotoCheck.cs
namespace Elevator.PhotoJunk.Site.Models.Album
{
	using Elevator.PhotoJunk.Site.Models.Photo;

	public class PhotoCheck
	{
		public PhotoThumbnail Photo { get; set; }
		public bool Checked { get; set; }
	}
}

Elevator.PhotoJunk.Site/Models/Album/UserAlbumsModel.cs
namespace Elevator.PhotoJunk.Site.Models.Album
{
	using Elevator.PhotoJunk.Logic.Pagination;

	public class UserAlbumsModel
	{
		public string UserName { get; set; }
		public PagedData<AlbumThumbnail> Albums { get; set; }
	}
}

Elevator.PhotoJunk.Site/Controllers/AlbumController.cs
namespace Elevator.PhotoJunk.Site.Controllers
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Web.Mvc;
	using System.Web.Routing;
	using AutoMapper;
	using Elevator.PhotoJunk.Logic.Entities;
	using Elevator.PhotoJunk.Logic.Pagination;
	using Elevator.PhotoJunk.Logic.Services.Abstract;
	using Elevator.PhotoJunk.Site.Filters;
	using Elevator.PhotoJunk.Site.Helpers;
	using Elevator.PhotoJunk.Site.Models.Album;
	using Elevator.PhotoJunk.Site.Models.Photo;
	using Ninject;
	using SysImage = System.Drawing.Image;

	[HandleExceptionFilter(View = "ErrorServer")]
	public class AlbumController : Controller
	{
		[Inject]
		public IAlbumService AlbumService { get; set; }

		[Inject]
		public IPhotoService PhotoService { get; set; }

		[Inject]
		public IUserService UserService { get; set; }

		[Inject]
		public IImageService ImageService { get; set; }

		[Inject]
		public ImageHelper ImageHelper { get; set; }

		[HttpGet]
		public ActionResult Index()
		{
			PagedData<AlbumThumbnail> thumbnails = GetIndexPage("", 0);
			return View(thumbnails);
		}

		[HttpPost]
		public ActionResult IndexPage(string keyWords, int page)
		{
			PagedData<AlbumThumbnail> thumbnails = GetIndexPage(keyWords, page);
			return PartialView("AlbumsListPartial", thumbnails);
		}

		private PagedData<AlbumThumbnail> GetIndexPage(string keyWords, int page)
		{
			int numberOfThumbnails = ConfigHelper.NumberOfThumbnailsForSpecializedPage;

			PagedData<Album> albums = string.IsNullOrEmpty(keyWords)
				? AlbumService.GetAlbums(page, numberOfThumbnails)
				: AlbumService.FilterAlbumsByKeywords(keyWords, page, numberOfThumbnails);

			return PagedMapper.Map<Album, AlbumThumbnail>(albums);
		}

		[HttpGet]
		[Authorize]
		public ActionResult MyAlbums()
		{
			PagedData<AlbumThumbnail> thumbnails = GetAlbumsByUserPage(User.Identity.Name, 0);
			return View(thumbnails);
		}

		[HttpGet]
		public ActionResult AlbumsByUser(string userName)
		{
			PagedData<AlbumThumbnail> thumbnails = GetAlbumsByUserPage(userName, 0);

			UserAlbumsModel model = new UserAlbumsModel
			{
				UserName = userName,
				Albums = thumbnails
			};
			return View(model);
		}

		[HttpPost]
		public ActionResult AlbumsByUserPage(string userName, int page)
		{
			PagedData<AlbumThumbnail> thumbnails = GetAlbumsByUserPage(userName, page);
			return PartialView("AlbumsAnonymousListPartial", thumbnails);
		}

		private PagedData<AlbumThumbnail> GetAlbumsByUserPage(string userName, int page)
		{
			User author = UserService.GetUserByNickname(userName);
			PagedData<Album> albums = AlbumService.FilterAlbumsByAuthor(author.IdUser, page,
				ConfigHelper.NumberOfThumbnailsForSpecializedPage);

			return PagedMapper.Map<Album, AlbumThumbnail>(albums);
		}

		[HttpGet]
		public ActionResult Search()
		{
			AlbumSearchModel model = new AlbumSearchModel();
			return View(model);
		}

		[HttpPost]
		public ActionResult SearchPage(AlbumSearchModel model, int page)
		{
			PagedData<Album> albums = AlbumService.FilterAlbums(model.Title, model.Descriprion, model.AuthorName, page,
				ConfigHelper.NumberOfThumbnailsForSpecializedPage);

			PagedData<AlbumThumbnail> thumbnails = PagedMapper.Map<Album, AlbumThumbnail>(albums);
			return PartialView("AlbumsListPartial", thumbnails);
		}

		[HttpGet]
		public ActionResult Show(Guid id)
		{
			Album album = AlbumService.GetAlbumById(id);
			AlbumShowModel model = Mapper.Map<AlbumShowModel>(album);
			return View(model);
		}

		[HttpGet]
		public ActionResult ShowByName(string name)
		{
			Album album = AlbumService.GetAlbumByTitle(name);
			AlbumShowModel model = Mapper.Map<AlbumShowModel>(album);
			return View("Show", model);
		}

		[HttpPost]
		public ActionResult PhotosInAlbumPage(string albumName, int page)
		{
			Album album = AlbumService.GetAlbumByTitle(albumName);
			PagedData<Photo> photos = PhotoService.FilterPhotosByAlbum(album.IdAlbum, page,
				ConfigHelper.NumberOfThumbnailsForSpecializedPage);
			PagedData<PhotoThumbnail> thumbnails = PagedMapper.Map<Photo, PhotoThumbnail>(photos);

			return PartialView("PhotosAnonymousListPartial", thumbnails);
		}

		[HttpGet]
		public ActionResult Edit(Guid id)
		{
			Album album = AlbumService.GetAlbumById(id);
			AlbumEditModel model = Mapper.Map<AlbumEditModel>(album);
			return View(model);
		}

		[HttpGet]
		public ActionResult Create()
		{
			return View("Edit", CreateAlbumEditModel());
		}

		[HttpGet]
		public ActionResult Manage(Guid id)
		{
			Album album = AlbumService.GetAlbumById(id);
			User author = UserService.GetUserByNickname(User.Identity.Name);

			HashSet<Guid> photosInAlbum =
				new HashSet<Guid>(PhotoService.FilterPhotosByAlbum(id, 0, int.MaxValue).Select(p => p.IdPhoto));
			IEnumerable<Photo> photosOfUser = PhotoService.FilterPhotosByAuthor(author.IdUser, 0, int.MaxValue);

			List<PhotoCheck> photoChecks = photosOfUser.Select(photo => new PhotoCheck
			{
				Checked = photosInAlbum.Contains(photo.IdPhoto),
				Photo = Mapper.Map<PhotoThumbnail>(photo)
			}).ToList();

			AlbumManageModel albumManageModel = new AlbumManageModel
			{
				Album = Mapper.Map<AlbumThumbnail>(album),
				Photos = photoChecks
			};

			return View(albumManageModel);
		}

		[HttpPost]
		public ActionResult Manage(AlbumManageModel model)
		{
			Album album = AlbumService.GetAlbumById(model.Album.AlbumId);

			List<Guid> photosInAlbum =
				PhotoService.FilterPhotosByAlbum(album.IdAlbum, 0, int.MaxValue).Select(p => p.IdPhoto).ToList();
			List<Guid> checkedPhotos = model.Photos.Where(p => p.Checked).Select(p => p.Photo.PhotoId).ToList();

			List<Guid> photosToAdd = checkedPhotos.Where(id => !photosInAlbum.Contains(id)).ToList();
			List<Guid> photosToRemove = photosInAlbum.Where(id => !checkedPhotos.Contains(id)).ToList();

			foreach (Guid photoId in photosToAdd)
				PhotoService.AddPhotoToAlbum(photoId, album.IdAlbum);

			foreach (Guid photoId in photosToRemove)
				PhotoService.RemovePhotoFromAlbum(photoId, album.IdAlbum);

			return RedirectToAction("Show", new RouteValueDictionary {{"id", album.IdAlbum}});
		}

		[HttpGet]
		public ActionResult Delete(Guid id)
		{
			AlbumService.DeleteAlbum(id);
			return RedirectToAction("Index");
		}

		[HttpPost]
		public ActionResult Save(AlbumEditModel model)
		{
			User author = UserService.GetUserById(model.AuthorId);
			if (!UserCanCreateAlbum(author))
			{
				ModelState.AddModelError("",
					string.Format("You are not allowed to create more than {0} albums. Get a premium account to ignore this limit.", ConfigHelper.MaxAlbumsForNonPremium));
			}

			if (ModelState.IsValid)
			{
				if (model.IsNew)
				{
					Album album = Mapper.Map<Album>(model);
					model.Id = AlbumService.SaveAlbum(album).IdAlbum;
				}
				else
				{
					Album album = AlbumService.GetAlbumById(model.Id);
					album = Mapper.Map(model, album);
					AlbumService.UpdateAlbum(album);
				}
				return RedirectToAction("Show", new RouteValueDictionary {{"id", model.Id}});
			}
			return View("Edit", model);
		}

		private bool UserCanCreateAlbum(User user)
		{
			PagedData<Album> albums = AlbumService.FilterAlbumsByAuthor(user.IdUser, 0, 1);
			return user.IsPremium || albums.TotalItems < ConfigHelper.MaxAlbumsForNonPremium;
		}

		private AlbumEditModel CreateAlbumEditModel()
		{
			string name = User.Identity.Name;
			User user = UserService.GetUserByNickname(name);
			return new AlbumEditModel
			{
				IsNew = true,
				Id = Guid.Empty,
				AuthorId = user.IdUser,
				Title = null,
				Description = null,
				CoverImageFileName = null
			};
		}
	}
}

Elevator.PhotoJunk.Site/Controllers/UserController.cs
namespace Elevator.PhotoJunk.Site.Controllers
{
	using System;
	using System.Web.Mvc;
	using AutoMapper;
	using Elevator.PhotoJunk.Logic.Entities;
	using Elevator.PhotoJunk.Logic.Entities.Abstract;
	using Elevator.PhotoJunk.Logic.Pagination;
	using Elevator.PhotoJunk.Logic.Services.Abstract;
	using Elevator.PhotoJunk.Site.Filters;
	using Elevator.PhotoJunk.Site.Helpers;
	using Elevator.PhotoJunk.Site.Models.Album;
	using Elevator.PhotoJunk.Site.Models.Auth;
	using Elevator.PhotoJunk.Site.Models.Photo;
	using Elevator.PhotoJunk.Site.Models.User;
	using Ninject;

	[Authorize]
	[HandleExceptionFilter(View = "ErrorServer")]
	public class UserController : Controller
	{
		[Inject]
		public IAlbumService AlbumService { get; set; }

		[Inject]
		public IPhotoService PhotoService { get; set; }

		[Inject]
		public IUserService UserService { get; set; }

		[Inject]
		public IImageService ImageService { get; set; }

		[Inject]
		public ImageHelper ImageHelper { get; set; }

		[HttpGet]
		public ActionResult Index()
		{
			PagedData<UserThumbnail> thumbnails = GetIndexPage("", 0);
			return View(thumbnails);
		}

		[HttpPost]
		public ActionResult IndexPage(string keyWords, int page)
		{
			PagedData<UserThumbnail> thumbnails = GetIndexPage(keyWords, page);
			return PartialView("UsersListPartial", thumbnails);
		}

		private PagedData<UserThumbnail> GetIndexPage(string keyWords, int page)
		{
			int numberOfThumbnails = ConfigHelper.NumberOfThumbnailsForSpecializedPage;

			PagedData<User> users = string.IsNullOrEmpty(keyWords)
				? UserService.GetUsers(0, 500)
				: UserService.FilterUsersByKeywords(keyWords, page, numberOfThumbnails);

			return PagedMapper.Map<User, UserThumbnail>(users);
		}

		[HttpGet]
		public ActionResult Search()
		{
			UserSearchModel model = new UserSearchModel
			{
				RegistrationPeriodStart = DateTime.Now.AddYears(-1),
				RegistrationPeriodEnd = DateTime.Now
			};
			return View(model);
		}

		[HttpPost]
		public ActionResult SearchPage(UserSearchModel model, int page)
		{
			PagedData<User> usersByAnyName = UserService.FilterUsersByAnyName(model.Email, model.Name, model.Location,
				model.Description, model.RegistrationPeriodStart, model.RegistrationPeriodEnd, model.IsPremium ? true : (bool?) null, page,
				ConfigHelper.NumberOfThumbnailsForSpecializedPage);

			PagedData<UserThumbnail> thumbnails = PagedMapper.Map<User, UserThumbnail>(usersByAnyName);
			return PartialView("UsersListPartial", thumbnails);
		}

		[HttpGet]
		public ActionResult Show(string name)
		{
			User user = UserService.GetUserByNickname(name);
			UserShowModel model = Mapper.Map<UserShowModel>(user);
			return View(model);
		}

		[HttpPost]
		public ActionResult PhotosByAuthorPage(Guid userId, int page)
		{
			PagedData<Photo> photos = PhotoService.FilterPhotosByAuthor(userId, page,
				ConfigHelper.NumberOfThumbnailsForNonSpecializedPage);
			PagedData<PhotoThumbnail> thumbnails = PagedMapper.Map<Photo, PhotoThumbnail>(photos);

			return PartialView("PhotosAnonymousListPartial", thumbnails);
		}

		[HttpPost]
		public ActionResult AlbumsByAuthorPage(Guid userId, int page)
		{
			PagedData<Album> albums = AlbumService.FilterAlbumsByAuthor(userId, page,
				ConfigHelper.NumberOfThumbnailsForNonSpecializedPage);
			PagedData<AlbumThumbnail> thumbnails = PagedMapper.Map<Album, AlbumThumbnail>(albums);

			return PartialView("AlbumsAnonymousListPartial", thumbnails);
		}

		[HttpGet]
		public ActionResult Manage(ManageMessage? message)
		{
			ViewBag.StatusMessage =
				message == ManageMessage.ChangePasswordSuccess
					? "Your password has been changed."
					: message == ManageMessage.SetPasswordSuccess
						? "Your password has been set."
						: message == ManageMessage.RemoveLoginSuccess
							? "The external login was removed."
							: "";
			ViewBag.ReturnUrl = Url.Action("Manage");


			User user = UserService.GetUserByNickname(User.Identity.Name);
			UserManageModel model = Mapper.Map<UserManageModel>(user);
			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Save(UserManageModel model)
		{
			if (ModelState.IsValid)
			{
				User user = UserService.GetUserByNickname(User.Identity.Name);
				user = Mapper.Map(model, user);

				if (model.AvatarImageFile != null)
				{
					IImage avatar = ImageHelper.CreateAndSaveImageFromHttpFile(model.AvatarImageFile);
					UserService.SetAvatar(user.IdUser, avatar.IdImage);
				}

				// ChangePassword will throw an exception rather than return false in certain failure scenarios.
				bool userUpdated = UserService.UpdateUser(user);
				if (userUpdated)
				{
					return RedirectToAction("Manage");
				}
				ModelState.AddModelError("", "Profile has not been saved. Error occured.");
			}

			// If we got this far, something failed, redisplay form
			return View("Manage", model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult ChangePassword(LocalPasswordModel model)
		{
			const bool hasLocalAccount = true;
			ViewBag.HasLocalPassword = hasLocalAccount;
			ViewBag.ReturnUrl = Url.Action("ChangePassword");
			if (ModelState.IsValid)
			{
				// ChangePassword will throw an exception rather than return false in certain failure scenarios.
				bool changePasswordSucceeded;
				try
				{
					User user = UserService.GetUserByNickname(User.Identity.Name);
					changePasswordSucceeded = UserService.ChangePassword(user, model.OldPassword, model.NewPassword);
				}
				catch (Exception)
				{
					changePasswordSucceeded = false;
				}

				if (changePasswordSucceeded)
				{
					return RedirectToAction("Manage", new {Message = ManageMessage.ChangePasswordSuccess});
				}
				ModelState.AddModelError("", "The current password is incorrect or the new password is invalid.");
			}

			// If we got this far, something failed, redisplay form
			return View("Manage");
		}

		public enum ManageMessage
		{
			NoMessage,
			ChangePasswordSuccess,
			SetPasswordSuccess,
			RemoveLoginSuccess,
		}
	}
}

Elevator.PhotoJunk.Site/Views/Album/AlbumsByUser.cshtml
@model Elevator.PhotoJunk.Site.Models.Album.UserAlbumsModel

@{
	ViewBag.Title = "Albums by " + Model.UserName;
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
	$().ready(function () {
		$(".ajax_result").on("click", ".page-number", function () {
			var userName = '@Model.UserName';
			var page = parseInt($(this).html()) - 1;

			FillAndSendRequest(userName, page);
		});
	});

	function FillAndSendRequest(userName, page) {
		$.ajax({
			type: 'POST',
			url: '@Url.Action("AlbumsByUserPage")',
			data: { "userName": userName, "page": page },
			success: function (data) {
				$(".ajax_result").html(data);
			}
		});
	}
</script>

<h2>
	Albums by <a href='@Url.Action("Show", "User", new {name = Model.UserName})'>@Model.UserName</a>
</h2>

<div class="ajax_result">
	@Html.Partial("AlbumsAnonymousListPartial", Model.Albums)
</div>

Elevator.PhotoJunk.Site/Views/Album/Edit.cshtml
@model Elevator.PhotoJunk.Site.Models.Album.AlbumEditModel

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

@{
	ViewBag.Title = "Edit";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model.IsNew)
{
	<h2>Add album</h2>
}
else
{
	<h2>Edit album</h2>
}

@if (!Model.IsNew)
{
	<div class="photo">
		<img src='@Url.Content(Model.CoverImageFileName)' alt="@Model.Title" class="photo_img" />
	</div>
}

@using (Html.BeginForm("Save", "Album", null, FormMethod.Post, new {@class = "form", enctype = "multipart/form-data"}))
{
	@Html.ValidationSummary()

	@Html.HiddenFor(m => m.Id)
	@Html.HiddenFor(m => m.IsNew)
	@Html.HiddenFor(m => m.AuthorId)

	<div class="form_row">
		<div class="form_label">@Html.LabelFor(m => m.CoverImageFile)</div>
		<div class="form_field">@Html.TextBoxFor(m => m.CoverImageFile, new {@class = "file", type = "file"})</div>
	</div>
	<div class="form_row">
		<div class="form_label">@Html.LabelFor(m => m.Title)</div>
		<div class="form_field">@Html.TextBoxFor(m => m.Title, new {@class = "line"})</div>
	</div>
	<div class="form_row">
		<div class="form_label">@Html.LabelFor(m => m.Description)</div>
		<div class="form_field">@Html.TextAreaFor(m => m.Description, new {@class = "multiline"})</div>
	</div>
	<input type="submit" value="Save album" />
}

Elevator.PhotoJunk.Site/Views/Album/Manage.cshtml
@model Elevator.PhotoJunk.Site.Models.Album.AlbumManageModel

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

@{
	ViewBag.Title = "ManagePhotos";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Select photos for album "@Model.Album.Title"</h2>


<div class="album">
	<img src='@Url.Content(Model.Album.CoverFileName)' alt="@Model.Album.Title" class="photo_img" />
</div>

@using (Html.BeginForm("Manage", "Album", null, FormMethod.Post))
{
	@Html.ValidationSummary()
	@Html.HiddenFor(m => m.Album.AlbumId)

	<div class="thumbnail_container work_area">
		@for (int i = 0; i < Model.Photos.Count; ++i)
		{
			<div class="thumb">
				@Html.CheckBoxFor(m => m.Photos[i].Checked)
				@Html.HiddenFor(m => m.Photos[i].Photo.PhotoId)
				<a href='@Url.Action("Show", "Photo", new RouteValueDictionary {{"id", Model.Photos[i].Photo.PhotoId}})'>
					<img src='@Url.Content(Model.Photos[i].Photo.ImageFileName)' />
				</a>
				@Model.Photos[i].Photo.Title
			</div>
		}
	</div>
	<input type="submit" value="Save album" />
}

Elevator.PhotoJunk.Site/Views/Album/MyAlbums.cshtml
@model Elevator.PhotoJunk.Logic.Pagination.PagedData<Elevator.PhotoJunk.Site.Models.Album.AlbumThumbnail>

@{
	ViewBag.Title = "Your albums";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
	$().ready(function () {
		$(".ajax_result").on("click", ".page-number", function () {
			var userName = '@User.Identity.Name';
			var page = parseInt($(this).html()) - 1;

			FillAndSendRequest(userName, page);
		});
	});

	function FillAndSendRequest(userName, page) {
		$.ajax({
			type: 'POST',
			url: '@Url.Action("AlbumsByUserPage")',
			data: { "userName": userName, "page": page },
			success: function (data) {
				$(".ajax_result").html(data);
			}
		});
	}
</script>

@if (Request.IsAuthenticated)
{
	<h2>
		Your albums
	</h2>
	<a href='@Url.Action("Create", "Album")'>Add new one</a>

	<div class="ajax_result">
		@Html.Partial("AlbumsAnonymousListPartial", Model)
	</div>
}
else
{
	<h2>
		Please log in first
	</h2>
}

Elevator.PhotoJunk.Site/Views/Album/Show.cshtml
@model Elevator.PhotoJunk.Site.Models.Album.AlbumShowModel

@{
	ViewBag.Title = "Album: " + Model.Title;
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
	$().ready(function () {
		$(".ajax_result").on("click", ".page-number", function () {
			var albumName = '@Model.Title';
			var page = parseInt($(this).html()) - 1;

			FillAndSendRequest(albumName, page);
		});
	});

	function FillAndSendRequest(albumName, page) {
		$.ajax({
			type: 'POST',
			url: '@Url.Action("PhotosInAlbumPage")',
			data: { "albumName": albumName, "page": page },
			dataType: 'html',
			success: function (data) {
				$(".ajax_result").html(data);
			}
		});
	}
</script>

<h2>@Model.Title</h2>

@Html.HiddenFor(model => model.Id)
@Html.HiddenFor(model => model.AuthorId)
@Html.HiddenFor(model => model.AuthorEmail)

@if (Request.IsAuthenticated && User.Identity.Name == Model.AuthorName)
{
	<div class="context_menu">
		<a class="context_menu_item" href='@Url.Action("Edit", new {id = Model.Id})'>
			Edit
		</a>
		<a class="context_menu_item" href='@Url.Action("Manage", new {id = Model.Id})'>
			Manage
		</a>
		<a class="context_menu_item" href='@Url.Action("Delete", new {id = Model.Id})'>
			Delete
		</a>
	</div>
}

<div class="album">
	<img src='@Url.Content(Model.CoverImageFileName)' alt="@Model.Title" class="photo_img" />
</div>

<a class="link"
   onclick="return ShowShareWindow('@Url.RouteUrl("ShortAlbumRef", new RouteValueDictionary {{"name", Model.Title}}, "http", "localhost")');"
   href='@Url.RouteUrl("ShortAlbumRef", new RouteValueDictionary {{"name", Model.Title}}, "http", "localhost")'>
	Share
</a>

<p class="card_row">
	<b class="card_label">Author:</b>
	@if (Request.IsAuthenticated && User.Identity.Name == Model.AuthorName)
	{
		@:&nbsp;you
	}
	else
	{
		@:&nbsp;<a href='@Url.Action("Show", "User", new {name = Model.AuthorName})'>@Model.AuthorName</a>
	}
</p>
<p class="card_row">
	<b class="card_label">Description:</b>&nbsp;@Model.Description
</p>
<p class="card_row">
	<b class="card_label">Upload date:</b>&nbsp;@Model.UploadDate
</p>


@if (Model.Photos != null)
{
	if (Model.Photos.Any())
	{
		<h2>Photos:</h2>
	<div class="ajax_result">
		@Html.Partial("PhotosListPartial", Model.Photos)
	</div>
	}
	else
	{
		<h2><a href='@Url.Action("Manage", new {id = Model.Id})'>Add</a> some photos!</h2>
	}
}