Elevator.PhotoJunk.Site/Models/Photo/PhotoEditModel.cs
namespace Elevator.PhotoJunk.Site.Models.Photo
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.Web;
	using Elevator.PhotoJunk.Site.Validators;

	[PhotoEditModel]
	public class PhotoEditModel
	{
		public bool IsNew { get; set; }

		public Guid Id { get; set; }
		public Guid AuthorId { get; set; }

		[Required]
		[Display(Name = "Title")]
		[DataType(DataType.Text)]
		public string Title { get; set; }

		[Display(Name = "Place")]
		[DisplayFormat(ConvertEmptyStringToNull = false)]
		[DataType(DataType.Text)]
		public string Place { get; set; }

		[Display(Name = "Description")]
		[DisplayFormat(ConvertEmptyStringToNull = false)]
		[DataType(DataType.MultilineText)]
		public string Description { get; set; }

		[Display(Name = "Camera")]
		[DisplayFormat(ConvertEmptyStringToNull = false)]
		[DataType(DataType.Text)]
		public string Camera { get; set; }

		[Display(Name = "Focal length")]
		[DataType(DataType.Text)]
		public double FocalLength { get; set; }

		[Display(Name = "Aperture size")]
		[DataType(DataType.Text)]
		public double ApertureSize { get; set; }

		[Display(Name = "Iso speed")]
		[DataType(DataType.Text)]
		public int IsoSpeed { get; set; }

		[Display(Name = "Flash")]
		public bool Flash { get; set; }

		[Display(Name = "Image")]
		[FileSize("MaxImageSizeKB")]
		[FileMimeType("SupportedImageMimeTypes")]
		public HttpPostedFileBase FullImageFile { get; set; }
		public string ImageFileName { get; set; }
		public string FullImageFileName { get; set; }

	}
}

Elevator.PhotoJunk.Site/Models/Photo/PhotoSearchModel.cs
namespace Elevator.PhotoJunk.Site.Models.Photo
{
	using System.ComponentModel.DataAnnotations;
	using Elevator.PhotoJunk.Logic.Pagination;

	public class PhotoSearchModel
	{
		[Display(Name = "Title")]
		[DataType(DataType.Text)]
		public string Title { get; set; }

		[Display(Name = "Descriprion")]
		[DataType(DataType.MultilineText)]
		public string Descriprion { get; set; }

		[Display(Name = "Place")]
		[DataType(DataType.Text)]
		public string Place { get; set; }

		[Display(Name = "Camera")]
		[DataType(DataType.Text)]
		public string Camera { get; set; }

		[Display(Name = "Author name")]
		[DataType(DataType.Text)]
		public string AuthorName { get; set; }
	}
}

Elevator.PhotoJunk.Site/Models/Photo/PhotoShowModel.cs
namespace Elevator.PhotoJunk.Site.Models.Photo
{
	using System;

	public class PhotoShowModel
	{
		public Guid Id { get; set; }
		public string AuthorName { get; set; }
		public string AuthorEmail { get; set; }
		public string Title { get; set; }
		public string Place { get; set; }
		public DateTime UploadDate { get; set; }

		public string Description { get; set; }
		public string Camera { get; set; }
		public double FocalLength { get; set; }
		public double ApertureSize { get; set; }
		public int IsoSpeed { get; set; }
		public bool Flash { get; set; }

		public int Likes { get; set; }
		public int Dislikes { get; set; }

		public bool CanVote { get; set; }

		public string ImageFileName { get; set; }
		public string FullImageFileName { get; set; }
	}
}

Elevator.PhotoJunk.Site/Models/Photo/PhotoThumbnail.cs
namespace Elevator.PhotoJunk.Site.Models.Photo
{
	using System;

	public class PhotoThumbnail
	{
		public Guid PhotoId { get; set; }
		public string AuthorName { get; set; }
		public string AuthorEmail { get; set; }
		public string Title { get; set; }
		public string ImageFileName { get; set; }
	}
}

Elevator.PhotoJunk.Site/Models/Photo/UserPhotosModel.cs
namespace Elevator.PhotoJunk.Site.Models.Photo
{
	using Elevator.PhotoJunk.Logic.Pagination;

	public class UserPhotosModel
	{
		public string UserName { get; set; }
		public PagedData<PhotoThumbnail> Photos { get; set; }
	}
}

Elevator.PhotoJunk.Site/Controllers/PhotoController.cs
namespace Elevator.PhotoJunk.Site.Controllers
{
	using System;
	using System.Web.Mvc;
	using System.Web.Routing;
	using AutoMapper;
	using Elevator.PhotoJunk.Logic.Entities;
	using Elevator.PhotoJunk.Logic.Pagination;
	using Elevator.PhotoJunk.Logic.Services.Abstract;
	using Elevator.PhotoJunk.Site.Filters;
	using Elevator.PhotoJunk.Site.Helpers;
	using Elevator.PhotoJunk.Site.Models.Photo;
	using Ninject;
	using SysImage = System.Drawing.Image;

	[HandleExceptionFilter(View = "ErrorServer")]
	public class PhotoController : Controller
	{
		//
		// GET: /Photos/
		[Inject]
		public IPhotoService PhotoService { get; set; }

		[Inject]
		public IUserService UserService { get; set; }

		[Inject]
		public IImageService ImageService { get; set; }

		[Inject]
		public IVoteService VoteService { get; set; }

		[Inject]
		public ImageHelper ImageHelper { get; set; }

		[HttpGet]
		public ActionResult Index()
		{
			PagedData<PhotoThumbnail> thumbnails = GetIndexPage("", 0);
			return View(thumbnails);
		}

		[HttpPost]
		public ActionResult IndexPage(string keyWords, int page)
		{
			PagedData<PhotoThumbnail> thumbnails = GetIndexPage(keyWords, page);
			return PartialView("PhotosListPartial", thumbnails);
		}

		private PagedData<PhotoThumbnail> GetIndexPage(string keyWords, int page)
		{
			int numberOfThumbnails = ConfigHelper.NumberOfThumbnailsForSpecializedPage;

			PagedData<Photo> photos = string.IsNullOrEmpty(keyWords)
				? PhotoService.GetPhotos(page, numberOfThumbnails)
				: PhotoService.FilterPhotosByKeywords(keyWords, page, numberOfThumbnails);

			return PagedMapper.Map<Photo, PhotoThumbnail>(photos);
		}

		[HttpGet]
		[Authorize]
		public ActionResult MyPhotos()
		{
			PagedData<PhotoThumbnail> thumbnails = GetPhotosByUserPage(User.Identity.Name, 0);
			return View(thumbnails);
		}

		[HttpGet]
		public ActionResult PhotosByUser(string userName)
		{
			PagedData<PhotoThumbnail> thumbnails = GetPhotosByUserPage(userName, 0);

			UserPhotosModel model = new UserPhotosModel
			{
				UserName = userName,
				Photos = thumbnails
			};
			return View(model);
		}

		[HttpPost]
		public ActionResult PhotosByUserPage(string userName, int page)
		{
			PagedData<PhotoThumbnail> thumbnails = GetPhotosByUserPage(userName, page);
			return PartialView("PhotosAnonymousListPartial", thumbnails);
		}

		private PagedData<PhotoThumbnail> GetPhotosByUserPage(string userName, int page)
		{
			User author = UserService.GetUserByNickname(userName);
			PagedData<Photo> photos = PhotoService.FilterPhotosByAuthor(author.IdUser, page,
				ConfigHelper.NumberOfThumbnailsForSpecializedPage);

			return PagedMapper.Map<Photo, PhotoThumbnail>(photos);
		}

		[HttpGet]
		public ActionResult Search()
		{
			PhotoSearchModel model = new PhotoSearchModel();
			return View(model);
		}

		[HttpPost]
		public ActionResult SearchPage(PhotoSearchModel model, int page)
		{
			PagedData<Photo> photos = PhotoService.FilterPhotos(model.Title, model.Descriprion, model.Place, model.Camera,
				model.AuthorName, page, ConfigHelper.NumberOfThumbnailsForSpecializedPage);

			PagedData<PhotoThumbnail> thumbnails = PagedMapper.Map<Photo, PhotoThumbnail>(photos);
			return PartialView("PhotosListPartial", thumbnails);
		}

		[HttpGet]
		public ActionResult Show(Guid id)
		{
			Photo photo = PhotoService.GetPhoto(id);
			PhotoShowModel model = Mapper.Map<PhotoShowModel>(photo);

			if (Request.IsAuthenticated)
			{
				User user = UserService.GetUserByNickname(User.Identity.Name);
				model.CanVote = VoteService.UserCanVote(user.IdUser, id);
			}

			return View(model);
		}

		[Authorize]
		public ActionResult Like(Guid id)
		{
			return Vote(id, Logic.Services.Abstract.Vote.Like);
		}

		[Authorize]
		public ActionResult Dislike(Guid id)
		{
			return Vote(id, Logic.Services.Abstract.Vote.Dislike);
		}

		private ActionResult Vote(Guid photoId, Vote vote)
		{
			User user = UserService.GetUserByNickname(User.Identity.Name);
			bool canVote = VoteService.UserCanVote(user.IdUser, photoId);

			if (canVote)
				VoteService.VotePhoto(user.IdUser, photoId, vote);

			if (Request.IsAjaxRequest())
			{
				int currentLikes = VoteService.GetLikesForPhoto(photoId);
				int currentDislikes = VoteService.GetDislikesForPhoto(photoId);
				return Json(new {success = canVote, likes = currentLikes, dislikes = currentDislikes});
			}
			return Show(photoId);
		}

		[HttpGet]
		public ActionResult Edit(Guid id)
		{
			Photo photo = PhotoService.GetPhoto(id);
			PhotoEditModel model = Mapper.Map<PhotoEditModel>(photo);
			return View(model);
		}

		[HttpGet]
		public ActionResult Delete(Guid id)
		{
			PhotoService.DeletePhoto(id);
			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Add()
		{
			return View("Edit", CreatePhotoEditModel());
		}

		[HttpPost]
		public ActionResult Save(PhotoEditModel model)
		{
			User author = UserService.GetUserById(model.AuthorId);
			if (!UserCanCreatePhoto(author))
			{
				ModelState.AddModelError("",
					string.Format("You are not allowed to create more than {0} photos. Get a premium account to ignore this limit.",
						ConfigHelper.MaxPhotosForNonPremium));
			}

			if (ModelState.IsValid)
			{
				if (model.IsNew)
				{
					Photo photo = Mapper.Map<Photo>(model);
					model.Id = PhotoService.SavePhoto(photo).IdPhoto;
				}
				else
				{
					Photo photo = PhotoService.GetPhoto(model.Id);
					photo = Mapper.Map(model, photo);
					PhotoService.UpdatePhoto(photo);
				}
				return RedirectToAction("Show", new RouteValueDictionary {{"id", model.Id}});
			}
			return View("Edit", model);
		}

		private bool UserCanCreatePhoto(User user)
		{
			PagedData<Photo> photos = PhotoService.FilterPhotosByAuthor(user.IdUser, 0, 1);
			return user.IsPremium || photos.TotalItems < ConfigHelper.MaxPhotosForNonPremium;
		}

		private PhotoEditModel CreatePhotoEditModel()
		{
			string name = User.Identity.Name;
			User user = UserService.GetUserByNickname(name);
			return new PhotoEditModel
			{
				Id = Guid.Empty,
				Title = null,
				Place = null,
				Description = null,
				Camera = null,
				FocalLength = 0,
				ApertureSize = 0,
				IsoSpeed = 0,
				Flash = false,
				AuthorId = user.IdUser,
				ImageFileName = null,
				FullImageFileName = null,
				IsNew = true
			};
		}
	}
}

Elevator.PhotoJunk.Site/Controllers/UserController.cs
namespace Elevator.PhotoJunk.Site.Controllers
{
	using System;
	using System.Web.Mvc;
	using AutoMapper;
	using Elevator.PhotoJunk.Logic.Entities;
	using Elevator.PhotoJunk.Logic.Entities.Abstract;
	using Elevator.PhotoJunk.Logic.Pagination;
	using Elevator.PhotoJunk.Logic.Services.Abstract;
	using Elevator.PhotoJunk.Site.Filters;
	using Elevator.PhotoJunk.Site.Helpers;
	using Elevator.PhotoJunk.Site.Models.Album;
	using Elevator.PhotoJunk.Site.Models.Auth;
	using Elevator.PhotoJunk.Site.Models.Photo;
	using Elevator.PhotoJunk.Site.Models.User;
	using Ninject;

	[Authorize]
	[HandleExceptionFilter(View = "ErrorServer")]
	public class UserController : Controller
	{
		[Inject]
		public IAlbumService AlbumService { get; set; }

		[Inject]
		public IPhotoService PhotoService { get; set; }

		[Inject]
		public IUserService UserService { get; set; }

		[Inject]
		public IImageService ImageService { get; set; }

		[Inject]
		public ImageHelper ImageHelper { get; set; }

		[HttpGet]
		public ActionResult Index()
		{
			PagedData<UserThumbnail> thumbnails = GetIndexPage("", 0);
			return View(thumbnails);
		}

		[HttpPost]
		public ActionResult IndexPage(string keyWords, int page)
		{
			PagedData<UserThumbnail> thumbnails = GetIndexPage(keyWords, page);
			return PartialView("UsersListPartial", thumbnails);
		}

		private PagedData<UserThumbnail> GetIndexPage(string keyWords, int page)
		{
			int numberOfThumbnails = ConfigHelper.NumberOfThumbnailsForSpecializedPage;

			PagedData<User> users = string.IsNullOrEmpty(keyWords)
				? UserService.GetUsers(0, 500)
				: UserService.FilterUsersByKeywords(keyWords, page, numberOfThumbnails);

			return PagedMapper.Map<User, UserThumbnail>(users);
		}

		[HttpGet]
		public ActionResult Search()
		{
			UserSearchModel model = new UserSearchModel
			{
				RegistrationPeriodStart = DateTime.Now.AddYears(-1),
				RegistrationPeriodEnd = DateTime.Now
			};
			return View(model);
		}

		[HttpPost]
		public ActionResult SearchPage(UserSearchModel model, int page)
		{
			PagedData<User> usersByAnyName = UserService.FilterUsersByAnyName(model.Email, model.Name, model.Location,
				model.Description, model.RegistrationPeriodStart, model.RegistrationPeriodEnd, model.IsPremium ? true : (bool?) null, page,
				ConfigHelper.NumberOfThumbnailsForSpecializedPage);

			PagedData<UserThumbnail> thumbnails = PagedMapper.Map<User, UserThumbnail>(usersByAnyName);
			return PartialView("UsersListPartial", thumbnails);
		}

		[HttpGet]
		public ActionResult Show(string name)
		{
			User user = UserService.GetUserByNickname(name);
			UserShowModel model = Mapper.Map<UserShowModel>(user);
			return View(model);
		}

		[HttpPost]
		public ActionResult PhotosByAuthorPage(Guid userId, int page)
		{
			PagedData<Photo> photos = PhotoService.FilterPhotosByAuthor(userId, page,
				ConfigHelper.NumberOfThumbnailsForNonSpecializedPage);
			PagedData<PhotoThumbnail> thumbnails = PagedMapper.Map<Photo, PhotoThumbnail>(photos);

			return PartialView("PhotosAnonymousListPartial", thumbnails);
		}

		[HttpPost]
		public ActionResult AlbumsByAuthorPage(Guid userId, int page)
		{
			PagedData<Album> albums = AlbumService.FilterAlbumsByAuthor(userId, page,
				ConfigHelper.NumberOfThumbnailsForNonSpecializedPage);
			PagedData<AlbumThumbnail> thumbnails = PagedMapper.Map<Album, AlbumThumbnail>(albums);

			return PartialView("AlbumsAnonymousListPartial", thumbnails);
		}

		[HttpGet]
		public ActionResult Manage(ManageMessage? message)
		{
			ViewBag.StatusMessage =
				message == ManageMessage.ChangePasswordSuccess
					? "Your password has been changed."
					: message == ManageMessage.SetPasswordSuccess
						? "Your password has been set."
						: message == ManageMessage.RemoveLoginSuccess
							? "The external login was removed."
							: "";
			ViewBag.ReturnUrl = Url.Action("Manage");


			User user = UserService.GetUserByNickname(User.Identity.Name);
			UserManageModel model = Mapper.Map<UserManageModel>(user);
			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Save(UserManageModel model)
		{
			if (ModelState.IsValid)
			{
				User user = UserService.GetUserByNickname(User.Identity.Name);
				user = Mapper.Map(model, user);

				if (model.AvatarImageFile != null)
				{
					IImage avatar = ImageHelper.CreateAndSaveImageFromHttpFile(model.AvatarImageFile);
					UserService.SetAvatar(user.IdUser, avatar.IdImage);
				}

				// ChangePassword will throw an exception rather than return false in certain failure scenarios.
				bool userUpdated = UserService.UpdateUser(user);
				if (userUpdated)
				{
					return RedirectToAction("Manage");
				}
				ModelState.AddModelError("", "Profile has not been saved. Error occured.");
			}

			// If we got this far, something failed, redisplay form
			return View("Manage", model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult ChangePassword(LocalPasswordModel model)
		{
			const bool hasLocalAccount = true;
			ViewBag.HasLocalPassword = hasLocalAccount;
			ViewBag.ReturnUrl = Url.Action("ChangePassword");
			if (ModelState.IsValid)
			{
				// ChangePassword will throw an exception rather than return false in certain failure scenarios.
				bool changePasswordSucceeded;
				try
				{
					User user = UserService.GetUserByNickname(User.Identity.Name);
					changePasswordSucceeded = UserService.ChangePassword(user, model.OldPassword, model.NewPassword);
				}
				catch (Exception)
				{
					changePasswordSucceeded = false;
				}

				if (changePasswordSucceeded)
				{
					return RedirectToAction("Manage", new {Message = ManageMessage.ChangePasswordSuccess});
				}
				ModelState.AddModelError("", "The current password is incorrect or the new password is invalid.");
			}

			// If we got this far, something failed, redisplay form
			return View("Manage");
		}

		public enum ManageMessage
		{
			NoMessage,
			ChangePasswordSuccess,
			SetPasswordSuccess,
			RemoveLoginSuccess,
		}
	}
}

Elevator.PhotoJunk.Site/Views/Photo/Edit.cshtml
@model Elevator.PhotoJunk.Site.Models.Photo.PhotoEditModel

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

@{
	ViewBag.Title = "Edit";
	UICulture = "en-US"; Culture = "en-US"; // for correct decimal fields displaying
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model.IsNew)
{
    <h2>Add photo</h2>
}
else
{
    <h2>Edit photo</h2>
}

@if (!Model.IsNew)
{
    <div class="photo">
		<a href='@Url.Content(Model.FullImageFileName)'>
			<img src='@Url.Content(Model.ImageFileName)' alt="@Model.Title" class="photo_img" />
		</a>
    </div>
}

@using (Html.BeginForm("Save", "Photo", null, FormMethod.Post, new { @class = "form", enctype = "multipart/form-data"}))
{
    @Html.ValidationSummary()

    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.IsNew)
    @Html.HiddenFor(m => m.AuthorId)

    <fieldset>
        <legend>Photo info</legend>
        @if (Model.IsNew)
        {
            <div class="form_row">
                <div class="form_label">@Html.LabelFor(m => m.FullImageFile)</div>
                <div class="form_field">@Html.TextBoxFor(m => m.FullImageFile, new { @class = "file", type = "file" })</div>
            </div>
        }
        <div class="form_row">
            <div class="form_label">@Html.LabelFor(m => m.Title)</div>
            <div class="form_field">@Html.TextBoxFor(m => m.Title, new { @class = "line" })</div>
        </div>
        <div class="form_row">
            <div class="form_label">@Html.LabelFor(m => m.Description)</div>
            <div class="form_field">@Html.TextAreaFor(m => m.Description, new { @class = "multiline" })</div>
        </div>
        <div class="form_row">
            <div class="form_label">@Html.LabelFor(m => m.Place)</div>
            <div class="form_field">@Html.TextBoxFor(m => m.Place, new { @class = "line" })</div>
        </div>
    </fieldset>
    <fieldset>
        <legend>Camera info</legend>
        <div class="form_row">
            <div class="form_label">@Html.LabelFor(m => m.Camera)</div>
            <div class="form_field">@Html.TextBoxFor(m => m.Camera, new { @class = "line" })</div>
        </div>
        <div class="form_row">
            <div class="form_label">@Html.LabelFor(m => m.FocalLength)</div>
            <div class="form_field">@Html.TextBoxFor(m => m.FocalLength, new { @class = "number", pattern = @"[0-9]+(,[0-9]+)?" })</div>
        </div>
        <div class="form_row">
            <div class="form_label">@Html.LabelFor(m => m.ApertureSize)</div>
            <div class="form_field">@Html.TextBoxFor(m => m.ApertureSize, new { @class = "number", pattern = @"[0-9]+(,[0-9]+)?"})</div>
        </div>
	    <div class="form_row">
		    <div class="form_label">@Html.LabelFor(m => m.IsoSpeed)</div>
		    <div class="form_field">@Html.TextBoxFor(m => m.IsoSpeed, new { @class = "number", pattern = @"[0-9]+(,[0-9]+)?" })</div>
	    </div>
		<div class="form_row">
			<div class="form_label"></div>
			<div class="form_field">
				@Html.CheckBoxFor(m => m.Flash)
				@Html.LabelFor(m => m.Flash, new { @class = "checkbox" })
			</div>
		</div>		
    </fieldset>

    <input type="submit" value="Save photo" />
}

Elevator.PhotoJunk.Site/Views/Photo/MyPhotos.cshtml
@model Elevator.PhotoJunk.Logic.Pagination.PagedData<Elevator.PhotoJunk.Site.Models.Photo.PhotoThumbnail>

@{
	ViewBag.Title = "Your photos";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
	$().ready(function () {
		$(".ajax_result").on("click", ".page-number", function () {
			var userName = '@User.Identity.Name';
			var page = parseInt($(this).html()) - 1;

			FillAndSendRequest(userName, page);
		});
	});

	function FillAndSendRequest(userName, page) {
		$.ajax({
			type: 'POST',
			url: '@Url.Action("PhotosByUserPage")',
			data: { "userName": userName, "page": page },
			success: function (data) {
				$(".ajax_result").html(data);
			}
		});
	}
</script>

@if (Request.IsAuthenticated)
{
	<h2>
		Your photos
	</h2>
	<a href='@Url.Action("Add", "Photo")'>Add new one</a>

	<div class="ajax_result">
		@Html.Partial("PhotosAnonymousListPartial", Model)
	</div>
}
else
{
	<h2>
		Please log in first
	</h2>
}

Elevator.PhotoJunk.Site/Views/Photo/PhotosByUser.cshtml
@model Elevator.PhotoJunk.Site.Models.Photo.UserPhotosModel

@{
	ViewBag.Title = "Photos by " + Model.UserName;
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
	$().ready(function () {
		$(".ajax_result").on("click", ".page-number", function () {
			var userName = '@Model.UserName';
			var page = parseInt($(this).html()) - 1;

			FillAndSendRequest(userName, page);
		});
	});

	function FillAndSendRequest(userName, page) {
		$.ajax({
			type: 'POST',
			url: '@Url.Action("PhotosByUserPage")',
			data: { "userName": userName, "page": page },
			success: function (data) {
				$(".ajax_result").html(data);
			}
		});
	}
</script>

<h2>
	Photos by <a href='@Url.Action("Show", "User", new {name = Model.UserName})'>@Model.UserName</a>
</h2>

<div class="ajax_result">
	@Html.Partial("PhotosAnonymousListPartial", Model.Photos)
</div>

Elevator.PhotoJunk.Site/Views/Photo/Show.cshtml
@model Elevator.PhotoJunk.Site.Models.Photo.PhotoShowModel

@section Scripts {
	@Scripts.Render("~/bundles/ajax")
}

@{
	ViewBag.Title = "Photo: " + Model.Title;
	Layout = "~/Views/Shared/_Layout.cshtml";


	AjaxOptions likeOptions = new AjaxOptions
	{
		Url = Url.Action("Like", new {id = Model.Id}),
		HttpMethod = "POST",
		OnSuccess = "OnVoteSuccess"
	};

	AjaxOptions dislikeOptions = new AjaxOptions
	{
		Url = Url.Action("Dislike", new {id = Model.Id}),
		HttpMethod = "POST",
		OnSuccess = "OnVoteSuccess"
	};
}

<script type="text/javascript">
	function OnVoteSuccess(data) {
		if (data.success) {
			$(".vote .votes-number").text(data.dislikes);
			$(".vote .likes-number").text(data.likes);
		}
	}
</script>

<h2>@Model.Title</h2>

@Html.HiddenFor(photo => photo.Id)
@Html.HiddenFor(photo => photo.AuthorEmail)

@if (Request.IsAuthenticated && User.Identity.Name == Model.AuthorName)
{
	<div class="context_menu">
		<a class="context_menu_item" href='@Url.Action("Edit", new {id = Model.Id})'>
			Edit
		</a>
		<a class="context_menu_item" href='@Url.Action("Delete", new {id = Model.Id})'>
			Delete
		</a>
	</div>
}

<div class="photo">
	<a href='@Url.Content(Model.FullImageFileName)'>
		<img src='@Url.Content(Model.ImageFileName)' alt="@Model.Title" class="photo_img" />
	</a>
</div>

<div class="vote-share">
	<div class="vote">
		<div class="like">
			@if (Model.CanVote)
			{
				@Ajax.ActionLink("+", "Like", new { id = Model.Id }, likeOptions);
			}
			<span id="dislikes-number">@Model.Likes</span>
		</div>
		<div class="dislike">
			<span id="likes-number">@Model.Dislikes</span>
			@if (Model.CanVote)
			{
				@Ajax.ActionLink("-", "Dislike", new { id = Model.Id }, dislikeOptions);
			}
		</div>
	</div>

	<div class="share">
		<a class="link"
		   onclick="return ShowShareWindow('@Url.RouteUrl("ShortPhotoRef", new RouteValueDictionary {{"id", Model.Id}}, "http", "localhost")');"
		   href='@Url.RouteUrl("ShortPhotoRef", new RouteValueDictionary {{"id", Model.Id}}, "http", "localhost")'>
			Share
		</a>
	</div>
</div>


	<p class="card_row">
		<b class="card_label">Author:</b>
		@if (Request.IsAuthenticated && User.Identity.Name == Model.AuthorName)
		{
			@:&nbsp;you
	   	} else { @: &nbsp;<a href='@Url.Action("Show", "User", new {name = Model.AuthorName})'>@Model.AuthorName</a>
	}
	</p>
	<p class="card_row">
		<b class="card_label">Description:</b>&nbsp;@Model.Description
	</p>
	<p class="card_row">
		<b class="card_label">Place:</b>&nbsp;@Model.Place
	</p>
	<p class="card_row">
		<b class="card_label">Uploaded:</b>&nbsp;@Model.UploadDate
	</p>
	<p class="card_row">
		<b class="card_label">Camera:</b>&nbsp;@Model.Camera
	</p>
	<p class="card_row">
		<b class="card_label">Focal length:</b>&nbsp;@Model.FocalLength
	</p>
	<p class="card_row">
		<b class="card_label">Aperture size:</b>&nbsp;@Model.ApertureSize
	</p>
	<p class="card_row">
		<b class="card_label">ISO speed:</b>&nbsp;@Model.IsoSpeed
	</p>
	<p class="card_row">
		<b class="card_label">@(Model.Flash ? "Flash" : "No flash")</b>
	</p>